services:
  # ----------------------------
  # HADOOP HDFS CLUSTER
  # ----------------------------
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870" # NameNode Web UI
      - "9000:9000" # IPC
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    volumes:
      - namenode_data:/hadoop/dfs/name

  secondarynamenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: secondarynamenode
    restart: always
    ports:
      - "9868:9868" # Secondary Web UI
    env_file:
      - ./hadoop.env
    environment:
      - HDFS_CONF_dfs_namenode_secondary_http_address=secondarynamenode:9868
    command: hdfs secondarynamenode
    volumes:
      - secondarynamenode_data:/hadoop/dfs/namesecondary

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    env_file:
      - ./hadoop.env
    volumes:
      - datanode1_data:/hadoop/dfs/data

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    env_file:
      - ./hadoop.env
    volumes:
      - datanode2_data:/hadoop/dfs/data

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    env_file:
      - ./hadoop.env
    volumes:
      - datanode3_data:/hadoop/dfs/data

  # ----------------------------
  # SPARK CLUSTER (bde2020)
  # ----------------------------
  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    restart: always
    ports:
      - "8080:8080" # Spark Master Web UI
      - "7077:7077" # Spark Master URL
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker1
    restart: always
    depends_on:
      - spark-master
    ports:
      - "8081:8081" # Worker 1 Web UI
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  spark-worker2:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker2
    restart: always
    depends_on:
      - spark-master
    ports:
      - "8082:8081" # Worker 2 Web UI (Mapped to host 8082)
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  spark-worker3:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker3
    restart: always
    depends_on:
      - spark-master
    ports:
      - "8083:8081" # Worker 3 Web UI (Mapped to host 8083)
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

volumes:
  namenode_data:
  secondarynamenode_data:
  datanode1_data:
  datanode2_data:
  datanode3_data: